### PR TITLE
#73 Add functional tests to dev

### PR DESCRIPTION
**Pull request by ealefad**
This request suggests to add functional test directory 'eqbtest' to dev branch.

### CODE REVIEW

**Comment by macterra** [comment]
Yikes 262 new files?! Can you give us an overview so we know what we're looking at?

**Comment by ealefad** [comment]
The content of the `equibit-core/eqbtest` folder is the same as `equibit-core/test`, which has the functional test framework and tests within it with one extra file: `equibit-core/eqbtest/functional/test_runner.sh` that runs all available functional tests.

**Comment by macterra** [comment]
Remind us why we need a copy of the test folder?

**Review by macterra — CHANGES_REQUESTED** [review]
Get checks to pass

**Comment by ealefad** [comment]
It was about the way of preserving and merging the original Bitcoin functional tests code - we continue our functional test development in a separate 'project/eqbtest' directory and observe BTC updates in the original 'project/test' since we haven't found a convenient way to do the C-like preprocessing (please refer to this document, Appendix A https://docs.google.com/document/d/1S0kmCweX-kbJow6DuuK7EWxA3S1cjv8soIfyzd3ukLc/).

**Comment by macterra** [comment]
Is it possible to get all checks to pass?

**Comment by ealefad** [comment]
Yes I suppose, I consider to apply re-branding related changes within 2 hours.

**Comment by ealefad** [comment]
There's a new PR https://github.com/Equibit/equibit-core/pull/91, closing this.

**Pull request closed without merging**
