### PR TITLE
#75 updating python code in build_msvc

### PR DESCRIPTION
**Pull request by r-soltani**
renaming bitcoin to equibit

### CODE REVIEW

**Review by macterra — CHANGES_REQUESTED** [review]
I think most of these commits have already been merged to dev. Also this branch has conflicts. Maybe start a new PR?

**Comment by r-soltani** [comment]
This PR renamed (deletes and adds) the files related to Visual Studio project.

**Comment by macterra** [comment]
OK after the merge from dev this PR is down to just the one python script as expected. What did you do to test it?

**Comment by r-soltani** [comment]
All projects build in VS

**Comment by macterra** [comment]
Right but did you try adding a source file to the Makefile, re-running the script and seeing if the VS project is properly updated?

**Comment by r-soltani** [comment]
The python code is no longer used, as the VS profiles are created and maintained. 
The python code references the bitcoin named libraries while the VS project uses equibit libraries.
List of libraries references by the python code:
    'libbitcoin_cli',
    'libbitcoin_common',
    'libbitcoin_crypto',
    'libbitcoin_server',
    'libbitcoin_util',
    'libbitcoin_wallet',
    'libbitcoin_zmq',

In order to re-use the python code we should rebrand the libraries to equibit in the Python script as well as the Makefiles, so that they are referencing the same names everywhere

**Pull request closed without merging**
